input_sources:
  l515_1:
    type: pointcloud
    topic: /l515_1/depth/color/points
    queue_size: 2
    publish_on_update: true
    sensor_processor:
      type: structured_light
      ignore_points_above: 0.3
      ignore_points_below: -0.5

  l515_2:
    type: pointcloud
    topic: /l515_2/depth/color/points
    queue_size: 2
    publish_on_update: true
    sensor_processor:
      type: structured_light
      ignore_points_above: 0.3
      ignore_points_below: -0.5

  d455_1:
    type: pointcloud
    topic: /d455_1/depth/color/points
    queue_size: 2
    publish_on_update: true
    sensor_processor:
      type: structured_light
      ignore_points_above: 0.3
      ignore_points_below: -0.5

  d455_2:
    type: pointcloud
    topic: /d455_2/depth/color/points
    queue_size: 2
    publish_on_update: true
    sensor_processor:
      type: structured_light
      ignore_points_above: 0.3
      ignore_points_below: -0.5

map_frame_id: "map"
robot_base_frame_id: "base_link"
num_callback_threads: 4

#postprocessor_pipeline_name: postprocessor_pipeline
#enable_continuous_cleanup: true
#postprocessor_num_threads: 1

robot_pose_with_covariance_topic: "/pose_with_covariance"
track_point_frame_id:                       "t265_pose_frame"
track_point_x:                              0.0
track_point_y:                              0.0
track_point_z:                              0.0

# Map.
length_in_x:                                7.5
length_in_y:                                7.5
position_x:                                 0.0
position_y:                                 0.0
resolution:                                 0.025

