// Structures and conversions generated by can.py.
#ifndef BOWIE_H
#define BOWIE_H
#include <stdint.h>
#include <ostream>
namespace can {

inline uint64_t read(uint64_t &buffer, uint8_t bits) {
  uint64_t res = buffer & ((1 << bits) - 1);
  return buffer >>= bits, res;
}

inline void write(uint64_t &buffer, uint8_t bits, uint64_t data) {
  buffer <<= bits;
  buffer |= data;
}

inline void to_buffer(uint8_t *buffer, uint64_t number) {
  *(uint64_t *)buffer = number;
}

inline uint64_t from_buffer(const uint8_t *buffer) {
  return *(const uint64_t *)buffer;
}

enum class FrameID {
  EStop = 0,
  MotorCommands = 1,
  ActuatorPosCommands = 2,
  ActuatorVelCommands = 3,
  ActuatorArmPos = 4,
  ActuatorBucketPos = 5,
  Error = 6,
  Lights = 7,
};

inline bool bool_deserialize(uint64_t buffer) { return buffer; }

inline uint64_t serialize(bool data) { return data; }

struct SingleMotorCommand {
  double speed;
};

inline SingleMotorCommand SingleMotorCommand_deserialize(uint64_t buffer) {
  SingleMotorCommand self;
  self.speed = (double)read(buffer, 16) * 0.03125047684443427 + -1024;
  return self;
}

inline uint64_t serialize(SingleMotorCommand data) {
  uint64_t ser = 0;
  write(ser, 16, (data.speed - -1024) / 0.03125047684443427);
  return ser;
}

inline std::ostream &operator<<(std::ostream &os, const SingleMotorCommand &self) {
  return os << "{ "
            << "speed = " << self.speed << ", "
            << "}";
}

enum class ErrorCode {
  ActuatorOutOfRange = 0,
  ActuatorOutOfAlignment = 1,
};

inline ErrorCode ErrorCode_deserialize(uint64_t buffer) {
  return (ErrorCode)buffer;
}

inline uint64_t serialize(ErrorCode data) {
  return (uint64_t)data;
}

inline std::ostream &operator<<(std::ostream &os, const ErrorCode &self) {
  switch (self) {
  case ErrorCode::ActuatorOutOfRange:
    os << "ErrorCode::ActuatorOutOfRange";
    break;
  case ErrorCode::ActuatorOutOfAlignment:
    os << "ErrorCode::ActuatorOutOfAlignment";
    break;
  }
  return os;
}

struct EStop {
  bool stop;
};

inline EStop EStop_deserialize(uint64_t buffer) {
  EStop self;
  self.stop = bool_deserialize(read(buffer, 1));
  return self;
}

inline uint64_t serialize(EStop data) {
  uint64_t ser = 0;
  write(ser, 1, serialize(data.stop));
  return ser;
}

inline std::ostream &operator<<(std::ostream &os, const EStop &self) {
  return os << "{ "
            << "stop = " << self.stop << ", "
            << "}";
}

struct MotorCommands {
  SingleMotorCommand left;
  SingleMotorCommand right;
};

inline MotorCommands MotorCommands_deserialize(uint64_t buffer) {
  MotorCommands self;
  self.left = SingleMotorCommand_deserialize(read(buffer, 16));
  self.right = SingleMotorCommand_deserialize(read(buffer, 16));
  return self;
}

inline uint64_t serialize(MotorCommands data) {
  uint64_t ser = 0;
  write(ser, 16, serialize(data.right));
  write(ser, 16, serialize(data.left));
  return ser;
}

inline std::ostream &operator<<(std::ostream &os, const MotorCommands &self) {
  return os << "{ "
            << "left = " << self.left << ", "
            << "right = " << self.right << ", "
            << "}";
}

struct ActuatorPosCommands {
  double arm_pos;
  double bucket_pos;
};

inline ActuatorPosCommands ActuatorPosCommands_deserialize(uint64_t buffer) {
  ActuatorPosCommands self;
  self.arm_pos = (double)read(buffer, 8) * 0.9803921568627451 + 0;
  self.bucket_pos = (double)read(buffer, 8) * 1.1764705882352942 + 0;
  return self;
}

inline uint64_t serialize(ActuatorPosCommands data) {
  uint64_t ser = 0;
  write(ser, 8, (data.bucket_pos - 0) / 1.1764705882352942);
  write(ser, 8, (data.arm_pos - 0) / 0.9803921568627451);
  return ser;
}

inline std::ostream &operator<<(std::ostream &os, const ActuatorPosCommands &self) {
  return os << "{ "
            << "arm_pos = " << self.arm_pos << ", "
            << "bucket_pos = " << self.bucket_pos << ", "
            << "}";
}

struct ActuatorVelCommands {
  double arm_vel;
  double bucket_vel;
};

inline ActuatorVelCommands ActuatorVelCommands_deserialize(uint64_t buffer) {
  ActuatorVelCommands self;
  self.arm_vel = (double)read(buffer, 8) * 0.0392156862745098 + -5;
  self.bucket_vel = (double)read(buffer, 8) * 0.0392156862745098 + -5;
  return self;
}

inline uint64_t serialize(ActuatorVelCommands data) {
  uint64_t ser = 0;
  write(ser, 8, (data.bucket_vel - -5) / 0.0392156862745098);
  write(ser, 8, (data.arm_vel - -5) / 0.0392156862745098);
  return ser;
}

inline std::ostream &operator<<(std::ostream &os, const ActuatorVelCommands &self) {
  return os << "{ "
            << "arm_vel = " << self.arm_vel << ", "
            << "bucket_vel = " << self.bucket_vel << ", "
            << "}";
}

struct ActuatorArmPos {
  double left_pos;
  double right_pos;
};

inline ActuatorArmPos ActuatorArmPos_deserialize(uint64_t buffer) {
  ActuatorArmPos self;
  self.left_pos = (double)read(buffer, 8) * 0.9803921568627451 + 0;
  self.right_pos = (double)read(buffer, 8) * 0.9803921568627451 + 0;
  return self;
}

inline uint64_t serialize(ActuatorArmPos data) {
  uint64_t ser = 0;
  write(ser, 8, (data.right_pos - 0) / 0.9803921568627451);
  write(ser, 8, (data.left_pos - 0) / 0.9803921568627451);
  return ser;
}

inline std::ostream &operator<<(std::ostream &os, const ActuatorArmPos &self) {
  return os << "{ "
            << "left_pos = " << self.left_pos << ", "
            << "right_pos = " << self.right_pos << ", "
            << "}";
}

struct ActuatorBucketPos {
  double pos;
};

inline ActuatorBucketPos ActuatorBucketPos_deserialize(uint64_t buffer) {
  ActuatorBucketPos self;
  self.pos = (double)read(buffer, 8) * 1.1764705882352942 + 0;
  return self;
}

inline uint64_t serialize(ActuatorBucketPos data) {
  uint64_t ser = 0;
  write(ser, 8, (data.pos - 0) / 1.1764705882352942);
  return ser;
}

inline std::ostream &operator<<(std::ostream &os, const ActuatorBucketPos &self) {
  return os << "{ "
            << "pos = " << self.pos << ", "
            << "}";
}

struct Error {
  ErrorCode error_code;
};

inline Error Error_deserialize(uint64_t buffer) {
  Error self;
  self.error_code = ErrorCode_deserialize(read(buffer, 1));
  return self;
}

inline uint64_t serialize(Error data) {
  uint64_t ser = 0;
  write(ser, 1, serialize(data.error_code));
  return ser;
}

inline std::ostream &operator<<(std::ostream &os, const Error &self) {
  return os << "{ "
            << "error_code = " << self.error_code << ", "
            << "}";
}

struct Lights {
  bool error;
  bool autonomy;
  bool motion;
  bool power;
};

inline Lights Lights_deserialize(uint64_t buffer) {
  Lights self;
  self.error = bool_deserialize(read(buffer, 1));
  self.autonomy = bool_deserialize(read(buffer, 1));
  self.motion = bool_deserialize(read(buffer, 1));
  self.power = bool_deserialize(read(buffer, 1));
  return self;
}

inline uint64_t serialize(Lights data) {
  uint64_t ser = 0;
  write(ser, 1, serialize(data.power));
  write(ser, 1, serialize(data.motion));
  write(ser, 1, serialize(data.autonomy));
  write(ser, 1, serialize(data.error));
  return ser;
}

inline std::ostream &operator<<(std::ostream &os, const Lights &self) {
  return os << "{ "
            << "error = " << self.error << ", "
            << "autonomy = " << self.autonomy << ", "
            << "motion = " << self.motion << ", "
            << "power = " << self.power << ", "
            << "}";
}
} // namespace can_BOWIE
#endif // BOWIE_H
